copy \Git\Windows-classic-samples\Samples\IME\cpp\SampleIME\ActiveLanguageProfileNotifySink.cpp
copy \Git\Windows-classic-samples\Samples\IME\cpp\SampleIME\BaseDictionaryEngine.cpp
copy \Git\Windows-classic-samples\Samples\IME\cpp\SampleIME\BaseDictionaryEngine.h
copy \Git\Windows-classic-samples\Samples\IME\cpp\SampleIME\BaseWindow.cpp
copy \Git\Windows-classic-samples\Samples\IME\cpp\SampleIME\BaseWindow.h
copy \Git\Windows-classic-samples\Samples\IME\cpp\SampleIME\ButtonWindow.cpp
copy \Git\Windows-classic-samples\Samples\IME\cpp\SampleIME\ButtonWindow.h
copy \Git\Windows-classic-samples\Samples\IME\cpp\SampleIME\CandidateListUIPresenter.cpp
copy \Git\Windows-classic-samples\Samples\IME\cpp\SampleIME\CandidateListUIPresenter.h
copy \Git\Windows-classic-samples\Samples\IME\cpp\SampleIME\CandidateWindow.cpp
copy \Git\Windows-classic-samples\Samples\IME\cpp\SampleIME\CandidateWindow.h
copy \Git\Windows-classic-samples\Samples\IME\cpp\SampleIME\Compartment.cpp
copy \Git\Windows-classic-samples\Samples\IME\cpp\SampleIME\Compartment.h
copy \Git\Windows-classic-samples\Samples\IME\cpp\SampleIME\Composition.cpp
copy \Git\Windows-classic-samples\Samples\IME\cpp\SampleIME\CompositionProcessorEngine.cpp
copy \Git\Windows-classic-samples\Samples\IME\cpp\SampleIME\CompositionProcessorEngine.h
copy \Git\Windows-classic-samples\Samples\IME\cpp\SampleIME\Define.h
copy \Git\Windows-classic-samples\Samples\IME\cpp\SampleIME\DictionaryParser.cpp
copy \Git\Windows-classic-samples\Samples\IME\cpp\SampleIME\DictionaryParser.h
copy \Git\Windows-classic-samples\Samples\IME\cpp\SampleIME\DictionarySearch.cpp
copy \Git\Windows-classic-samples\Samples\IME\cpp\SampleIME\DictionarySearch.h
copy \Git\Windows-classic-samples\Samples\IME\cpp\SampleIME\DisplayAttribute.cpp
copy \Git\Windows-classic-samples\Samples\IME\cpp\SampleIME\DisplayAttributeInfo.cpp
copy \Git\Windows-classic-samples\Samples\IME\cpp\SampleIME\DisplayAttributeInfo.h
copy \Git\Windows-classic-samples\Samples\IME\cpp\SampleIME\DisplayAttributeProvider.cpp
copy \Git\Windows-classic-samples\Samples\IME\cpp\SampleIME\DisplayString.h
copy \Git\Windows-classic-samples\Samples\IME\cpp\SampleIME\DllMain.cpp
copy \Git\Windows-classic-samples\Samples\IME\cpp\SampleIME\EditSession.cpp
copy \Git\Windows-classic-samples\Samples\IME\cpp\SampleIME\EditSession.h
copy \Git\Windows-classic-samples\Samples\IME\cpp\SampleIME\EndComposition.cpp
copy \Git\Windows-classic-samples\Samples\IME\cpp\SampleIME\EnumDisplayAttributeInfo.cpp
copy \Git\Windows-classic-samples\Samples\IME\cpp\SampleIME\EnumDisplayAttributeInfo.h
copy \Git\Windows-classic-samples\Samples\IME\cpp\SampleIME\EnumTfCandidates.cpp
copy \Git\Windows-classic-samples\Samples\IME\cpp\SampleIME\EnumTfCandidates.h
copy \Git\Windows-classic-samples\Samples\IME\cpp\SampleIME\File.cpp
copy \Git\Windows-classic-samples\Samples\IME\cpp\SampleIME\File.h
copy \Git\Windows-classic-samples\Samples\IME\cpp\SampleIME\FileMapping.cpp
copy \Git\Windows-classic-samples\Samples\IME\cpp\SampleIME\FileMapping.h
copy \Git\Windows-classic-samples\Samples\IME\cpp\SampleIME\FunctionProviderSink.cpp
copy \Git\Windows-classic-samples\Samples\IME\cpp\SampleIME\GetTextExtentEditSession.cpp
copy \Git\Windows-classic-samples\Samples\IME\cpp\SampleIME\GetTextExtentEditSession.h
copy \Git\Windows-classic-samples\Samples\IME\cpp\SampleIME\Globals.cpp
copy \Git\Windows-classic-samples\Samples\IME\cpp\SampleIME\Globals.h
copy \Git\Windows-classic-samples\Samples\IME\cpp\SampleIME\KeyEventSink.cpp
copy \Git\Windows-classic-samples\Samples\IME\cpp\SampleIME\KeyHandler.cpp
copy \Git\Windows-classic-samples\Samples\IME\cpp\SampleIME\KeyHandlerEditSession.cpp
copy \Git\Windows-classic-samples\Samples\IME\cpp\SampleIME\KeyHandlerEditSession.h
copy \Git\Windows-classic-samples\Samples\IME\cpp\SampleIME\KeyStateCategory.cpp
copy \Git\Windows-classic-samples\Samples\IME\cpp\SampleIME\KeyStateCategory.h
copy \Git\Windows-classic-samples\Samples\IME\cpp\SampleIME\LanguageBar.cpp
copy \Git\Windows-classic-samples\Samples\IME\cpp\SampleIME\LanguageBar.h
copy \Git\Windows-classic-samples\Samples\IME\cpp\SampleIME\pch.h
copy \Git\Windows-classic-samples\Samples\IME\cpp\SampleIME\Register.cpp
copy \Git\Windows-classic-samples\Samples\IME\cpp\SampleIME\RegKey.cpp
copy \Git\Windows-classic-samples\Samples\IME\cpp\SampleIME\RegKey.h
copy \Git\Windows-classic-samples\Samples\IME\cpp\SampleIME\resource.h
copy \Git\Windows-classic-samples\Samples\IME\cpp\SampleIME\SampleIME.cpp
copy \Git\Windows-classic-samples\Samples\IME\cpp\SampleIME\SampleIME.h
copy \Git\Windows-classic-samples\Samples\IME\cpp\SampleIME\SampleIME.rc
copy \Git\Windows-classic-samples\Samples\IME\cpp\SampleIME\SampleIMEBaseStructure.cpp
copy \Git\Windows-classic-samples\Samples\IME\cpp\SampleIME\SampleIMEBaseStructure.h
copy \Git\Windows-classic-samples\Samples\IME\cpp\SampleIME\SampleIMEStructureArray.h
copy \Git\Windows-classic-samples\Samples\IME\cpp\SampleIME\ScrollBarWindow.cpp
copy \Git\Windows-classic-samples\Samples\IME\cpp\SampleIME\ScrollBarWindow.h
copy \Git\Windows-classic-samples\Samples\IME\cpp\SampleIME\SearchCandidateProvider.cpp
copy \Git\Windows-classic-samples\Samples\IME\cpp\SampleIME\SearchCandidateProvider.h
copy \Git\Windows-classic-samples\Samples\IME\cpp\SampleIME\Server.cpp
copy \Git\Windows-classic-samples\Samples\IME\cpp\SampleIME\ShadowWindow.cpp
copy \Git\Windows-classic-samples\Samples\IME\cpp\SampleIME\ShadowWindow.h
copy \Git\Windows-classic-samples\Samples\IME\cpp\SampleIME\StartComposition.cpp
copy \Git\Windows-classic-samples\Samples\IME\cpp\SampleIME\TableDictionaryEngine.cpp
copy \Git\Windows-classic-samples\Samples\IME\cpp\SampleIME\TableDictionaryEngine.h
copy \Git\Windows-classic-samples\Samples\IME\cpp\SampleIME\TextEditSink.cpp
copy \Git\Windows-classic-samples\Samples\IME\cpp\SampleIME\TfInputProcessorProfile.cpp
copy \Git\Windows-classic-samples\Samples\IME\cpp\SampleIME\TfInputProcessorProfile.h
copy \Git\Windows-classic-samples\Samples\IME\cpp\SampleIME\TfTextLayoutSink.cpp
copy \Git\Windows-classic-samples\Samples\IME\cpp\SampleIME\TfTextLayoutSink.h
copy \Git\Windows-classic-samples\Samples\IME\cpp\SampleIME\ThreadFocusSink.cpp
copy \Git\Windows-classic-samples\Samples\IME\cpp\SampleIME\ThreadMgrEventSink.cpp
copy \Git\Windows-classic-samples\Samples\IME\cpp\SampleIME\TipCandidateList.cpp
copy \Git\Windows-classic-samples\Samples\IME\cpp\SampleIME\TipCandidateList.h
copy \Git\Windows-classic-samples\Samples\IME\cpp\SampleIME\TipCandidateString.cpp
copy \Git\Windows-classic-samples\Samples\IME\cpp\SampleIME\TipCandidateString.h
